from pydantic import BaseModel, Field, field_validator
from typing import Optional, List
from datetime import datetime
from uuid import UUID

class UserRequest(BaseModel):
    """
    Schema for the user's input to the medical chatbot.
    """
    user_id: Optional[str] = Field(
        None, description="Unique identifier for the user (optional, can be used for tracking)."
    )
    message: str = Field(
        ..., description="The medical-related question or request from the user."
    )
    timestamp: Optional[datetime] = Field(
        default_factory=datetime.utcnow,
        description="Timestamp of when the user sent the request."
    )


class MedicalAdvice(BaseModel):
    """
    Schema for a single piece of medical advice or information.
    """
    title: str = Field(..., description="Title or short summary of the medical advice.")
    description: str = Field(..., description="Detailed description of the advice or information.")
    references: Optional[List[str]] = Field(
        None, description="List of reference URLs or sources for this advice."
    )


class MedicalResponse(BaseModel):
    """
    Schema for the response from the medical chatbot.
    """
    request_id: str = Field(..., description="Unique identifier for the request, useful for tracing.")
    user_message: str = Field(..., description="The original message sent by the user.")
    response: List[MedicalAdvice] = Field(
        ..., description="List of medical advice or information generated by the chatbot."
    )
    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the chatbot generated the response."
    )
    confidence_score: Optional[float] = Field(
        None,
        description="Optional confidence score of the response (0.0 to 1.0), if available from AI model."
    )


class LoginRequest(BaseModel):
    email: str = Field(..., description="Email for login")
    password: str = Field(..., description="Password for login", min_length=8, max_length=64)
    
    @field_validator("password")
    def check_password_bytes(cls, v):
        if len(v.encode("utf-8")) > 72:
            raise ValueError("Password too long")
        return v

class TokenResponse(BaseModel):
    access_token: str = Field(..., description="JWT access token for authenticated requests")
    token_type: str = Field(..., description="Type of token, usually 'bearer'")
    

class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000)
    

class ChatResponse(BaseModel):
    session_id: UUID
    user_message: str
    ai_message: str
    is_emergency: bool
    
    
class ChatSessionsOut(BaseModel):
    id: UUID
    session_title: str | None
    is_closed: bool
    created_at: datetime
    

class ChatSessionsResponse(BaseModel):
    sessions: list[ChatSessionsOut]

class ChatMessagesOut(BaseModel):
    id: UUID
    sender: str
    message_text: str
    is_emergency: bool | None
    created_at: datetime


class ChatHistoryResponse(BaseModel):
    session_id: UUID
    messages: list[ChatMessagesOut]